apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort
  selector:
    app: bankapp
    version: blue   # change to green when needed
  selector:
    app: bankapp
    version: green
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007


