apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort
  selector:
    app: bankapp
    version: blue   # switch to green when needed
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007

